using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.Data.SqlClient; using RiceMillProject.Models;
namespace RiceMillProject.Controllers;
[Authorize(Roles="Admin")] public class DatabaseMapController(IConfiguration config):Controller
{
 private readonly string cs=config.GetConnectionString("DefaultConnection")??"";
 public IActionResult Index(){var m=new DatabaseSchemaMap();using var con=new SqlConnection(cs);con.Open();
 using(var cmd=new SqlCommand(@"SELECT t.name TableName,c.column_id,c.name ColumnName,TYPE_NAME(c.user_type_id) DataType,CASE WHEN pk.column_id IS NULL THEN 0 ELSE 1 END IsPK,ISNULL(rc.RecordCount,0) RecordCount FROM sys.tables t JOIN sys.columns c ON c.object_id=t.object_id LEFT JOIN(SELECT ic.object_id,ic.column_id FROM sys.indexes i JOIN sys.index_columns ic ON ic.object_id=i.object_id AND ic.index_id=i.index_id WHERE i.is_primary_key=1)pk ON pk.object_id=c.object_id AND pk.column_id=c.column_id LEFT JOIN(SELECT object_id,SUM(rows)RecordCount FROM sys.partitions WHERE index_id IN(0,1)GROUP BY object_id)rc ON rc.object_id=t.object_id ORDER BY t.name,c.column_id",con))using(var r=cmd.ExecuteReader()){DatabaseTableMap? t=null;while(r.Read()){var n=r["TableName"].ToString()!;if(t==null||t.Name!=n){t=new(){Name=n,RowCount=Convert.ToInt64(r["RecordCount"])};m.Tables.Add(t);}t.Columns.Add(new(){Name=r["ColumnName"].ToString()!,DataType=r["DataType"].ToString()!,IsPrimaryKey=Convert.ToBoolean(r["IsPK"])});}}
 using(var cmd=new SqlCommand(@"SELECT pt.name FT,pc.name FC,rt.name TT,rc.name TC FROM sys.foreign_key_columns f JOIN sys.tables pt ON pt.object_id=f.parent_object_id JOIN sys.columns pc ON pc.object_id=f.parent_object_id AND pc.column_id=f.parent_column_id JOIN sys.tables rt ON rt.object_id=f.referenced_object_id JOIN sys.columns rc ON rc.object_id=f.referenced_object_id AND rc.column_id=f.referenced_column_id",con))using(var r=cmd.ExecuteReader())while(r.Read())m.Relationships.Add(new(){FromTable=r["FT"].ToString()!,FromColumn=r["FC"].ToString()!,ToTable=r["TT"].ToString()!,ToColumn=r["TC"].ToString()!,IsEnforced=true});Infer(m);return View(m);}
 static void Infer(DatabaseSchemaMap m){var x=new Dictionary<string,(string,string)>(StringComparer.OrdinalIgnoreCase){{"BagTypeId",("m_BagType","BagTypeId")},{"CategoryId",("m_ItemCategory","CategoryId")},{"DepartmentId",("m_DepartmentMaster","DepartmentId")},{"GateId",("m_GateMaster","GateId")},{"InwardTypeId",("m_InwardTypeMaster","InwardTypeId")},{"ItemId",("m_Item","ItemId")},{"LocationId",("m_LocationMaster","LocationId")},{"OfficeId",("o05_office","OfficeId")},{"TargetOfficeId",("o05_office","OfficeId")},{"o10_postid",("o10_post","PostId")},{"StatusId",("m_StatusMaster","StatusId")},{"sa10_usertypeid",("sa10_usertype","UserTypeId")},{"VehicleId",("m_Vehicle","VehicleId")},{"VehicleTypeId",("m_VehicleTypeMaster","VehicleTypeId")},{"UnloadId",("t_UnloadTransaction","UnloadId")}};var p=new HashSet<string>(["PersonId","PartyId","DriverId","SupervisorId","MethId","WorkerId","GateManId","TestedBy","ReportedToPersonId"],StringComparer.OrdinalIgnoreCase);var names=m.Tables.Select(t=>t.Name).ToHashSet(StringComparer.OrdinalIgnoreCase);foreach(var t in m.Tables)foreach(var c in t.Columns){(string,string)? to=p.Contains(c.Name)?("p02_Person","PersonId"):c.Name.Equals("CreatedBy",StringComparison.OrdinalIgnoreCase)?("sa05_user","UserId"):c.Name.Equals("InwardNo",StringComparison.OrdinalIgnoreCase)&&t.Name!="t_InwardHeader"?("t_InwardHeader","InwardNo"):c.Name.Equals("RSTNumber",StringComparison.OrdinalIgnoreCase)&&t.Name!="t_GateEntry"?("t_GateEntry","RSTNumber"):x.TryGetValue(c.Name,out var v)?v:null;if(to!=null&&names.Contains(to.Value.Item1)&&t.Name!=to.Value.Item1&&!m.Relationships.Any(r=>r.FromTable==t.Name&&r.FromColumn==c.Name))m.Relationships.Add(new(){FromTable=t.Name,FromColumn=c.Name,ToTable=to.Value.Item1,ToColumn=to.Value.Item2});}}
}
